apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/rvennam/mylibertyproject:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/rvennam/mylibertyproject:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: mylibertyproject
        chartPath: charts/mylibertyproject
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/rvennam/mylibertyproject"
          image.tag: "{{.TAG}}"
